package:
  name: eqt
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}
  
source:
  path: ..

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False 
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  noarch: python

test:
  source_files:
    - ./test

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover -s test -v


requirements:
  build:
    - python
    - pip
    - sphinx
  run:
    - python
    - PySide6

about:
  home: https://github.com/paskino/qt-elements
  license: Apache 2.0
  summary: A number of templates and tools to develop Qt GUI's with Python effectively.
