package:
  name: eqt
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - pip
    - sphinx
  run:
    - python
    - pyside2

about:
  home: https://github.com/paskino/qt-elements
  license: Apache 2.0
  summary: A number of templates and tools to develop Qt GUI's with Python effectively.
