name: publish_conda

on:
  release:
    types: [published]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: paskino/conda-package-publish-action@v1.2.2
      with:
        subDir: 'conda'
        channels: '{conda-forge}'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
