name: publish_conda

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: paskino/conda-package-publish-action@v1.4.3
      with:
        subDir: 'conda'
        channels: 'conda-forge'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        test_all: ${{(github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || (github.ref == 'refs/heads/main')}}
        convert_win: false
        convert_osx: false
