name: build_conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: lauramurgatroyd/conda-package-publish-action@optional_publish
      with:
        subDir: 'conda'
        channels: 'conda-forge'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: False
